name: build-native-nuget
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-native-nuget.yml
  workflow_dispatch:
  
jobs:
  build-all:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - { title: win-x64,         rid: win-x64,   url: https://paddle-inference-lib.bj.bcebos.com/3.0.0/cxx_c/Windows/CPU/x86-64_avx-mkl-vs2019/paddle_inference_c.zip }
          # - { title: win-x64-cu118,   rid: win-x64,   url: https://paddle-inference-lib.bj.bcebos.com/3.0.0/cxx_c/Windows/GPU/x86-64_cuda11.8_cudnn8.6.0_trt8.5.1.7_mkl_avx_vs2019/paddle_inference_c.zip }
          # - { title: win-x64-cu126,   rid: win-x64,   url: https://paddle-inference-lib.bj.bcebos.com/3.0.0/cxx_c/Windows/GPU/x86-64_cuda12.6_cudnn9.5.1_trt10.5.0.18_mkl_avx_vs2019/paddle_inference_c.zip }
          - { title: linux-x64,       rid: linux-x64, url: https://paddle-inference-lib.bj.bcebos.com/3.0.0/cxx_c/Linux/CPU/gcc8.2_avx_mkl/paddle_inference_c.tgz }
          # - { title: linux-x64-cu118, rid: linux-x64, url: https://paddle-inference-lib.bj.bcebos.com/3.0.0/cxx_c/Linux/GPU/x86-64_gcc11.2_avx_mkl_cuda11.8_cudnn8.9.7-trt8.6.1.6/paddle_inference_c.tgz }
          # - { title: linux-x64-cu126, rid: linux-x64, url: https://paddle-inference-lib.bj.bcebos.com/3.0.0/cxx_c/Linux/GPU/x86-64_gcc11.2_avx_mkl_cuda12.6_cudnn9.5.1-trt10.5.0.18/paddle_inference_c.tgz }
          # - { title: osx-x64,         rid: osx-x64,   url: https://paddle-inference-lib.bj.bcebos.com/3.0.0/cxx_c/MacOS/x86-64_clang_avx_accelerate_blas/paddle_inference_c.tgz }
          # - { title: osx-arm64,       rid: osx-arm64, url: https://paddle-inference-lib.bj.bcebos.com/3.0.0/cxx_c/MacOS/m1_clang_noavx_accelerate_blas/paddle_inference_c.tgz }
  
    steps:
      - name: Download/Extract Paddle Inference C API Archive
        run: |
          wget -O paddle_inference_c.zip ${{ matrix.url }}
          if [[ "${{ matrix.rid }}" == "win-x64" ]]; then
              unzip paddle_inference_c.zip
          else
              tar -xzf paddle_inference_c.zip
          fi
          cd paddle_inference_c
          echo "::group::Extracted Paddle Inference C API Archive"
          ls -lR
          echo "::endgroup::"