name: main
on:
  push:
    branches:
      - master
      - feature/linux
    paths:
      - 'src/**'
      - .github/workflows/main.yml
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [windows-2022, ubuntu-22.04, ubuntu-22.04-arm, macos-13]
    steps:
    - uses: actions/checkout@v4
    - name: Setup NuGet Source
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        dotnet nuget list source

    - name: Build code
      run: dotnet build -c Test

    - name: Test
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          dotnet test ./tests/Sdcb.PaddleOCR.Tests/Sdcb.PaddleOCR.Tests.csproj -c Test --no-build --verbosity normal --filter 'Category!=WindowsOnly'
        elif [[ "${{ runner.os }}" == "Linux" ]]; then
          ulimit -c unlimited
          export GDB_STACKTRACE=1
          dotnet test ./tests/Sdcb.PaddleOCR.Tests/Sdcb.PaddleOCR.Tests.csproj -c Test --no-build --verbosity normal --filter 'Category!=WindowsOnly'
        else
          dotnet test ./tests/Sdcb.PaddleOCR.Tests/Sdcb.PaddleOCR.Tests.csproj -c Test --no-build --verbosity normal
        fi