name: main
on:
  push:
    branches:
      - master
      - feature/linux
    paths:
      - 'src/**'
      - .github/workflows/main.yml
  workflow_dispatch:
  
jobs:
  windows:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [windows-2022, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - name: Setup NuGet Source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          dotnet nuget list source
      - name: Build code
        run: dotnet build -c Release
      - name: ldd debug(linux only)
        if: matrix.runs-on == 'ubuntu-22.04'
        run: |
          ls -lR ./tests/Sdcb.PaddleOCR.Tests/bin/Release/net8.0/runtimes/linux-x64/native
          ldd ./tests/Sdcb.PaddleOCR.Tests/bin/Release/net8.0/runtimes/linux-x64/native/libpaddle_inference_c.so
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
