name: main
on:
  push:
    branches: [master, feature/3.1]
    paths: [src/**, tests/**, .github/workflows/main.yml]
  workflow_dispatch:

env:
  TEST_PROJECTS: "Sdcb.PaddleInference.Tests \
                  Sdcb.PaddleNLP.Lac.Tests \
                  Sdcb.PaddleOCR.Tests \
                  Sdcb.RotationDetector.Tests"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup NuGet Source
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        dotnet nuget list source

    - name: Build code
      run: dotnet build -c Debug -p:Optimize=true

    - name: Create test artifacts
      run: |
        for proj in $TEST_PROJECTS; do
          echo "::group::Create artifacts for $proj""
          dst="test-artifacts/$proj"
          mkdir -p "$dst"
          cp -r "tests/$proj/bin/Debug/net8.0/"* "$dst/"
          echo "::endgroup::"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: test-artifacts

  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2025, 
             ubuntu-22.04, ubuntu-24.04,
             ubuntu-22.04-arm, ubuntu-24.04-arm,
             macos-13, macos-14, macos-15]
    needs: build
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: test-artifacts

    - name: Test
      shell: bash
      run: |
        for proj in $TEST_PROJECTS; do
          echo "::group::Run $proj"
          dotnet test \
            "$PWD/test-artifacts/$proj/$proj.dll" \
            -c Debug --no-build --verbosity detailed -p:Optimize=true
          echo "::endgroup::"
        done