name: main
on:
  push:
    branches:
      - master
      - feature/linux
    paths:
      - 'src/**'
      - .github/workflows/main.yml
  workflow_dispatch:
  
jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        runs-on: [windows-2022, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - name: Setup NuGet Source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}
          dotnet nuget list source
      - name: Restore dependencies
        run: |
          dotnet restore
      - name: Build code
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
